In [ ]:
# Introduction to CNN
# Convolutional Neural Networks ---> It is working for image related data.


In [ ]:
# Images --->  Pixels(0-255) ---> 0Px(Black), 255Px(White)----->
# Normalize (0-1) ---> 0P x(black),1px(white)

In [ ]:
# Images


In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(1,50,9).reshape(3,3)

In [ ]:
a

array([[15, 12, 28],
       [33, 48, 31],
       [31,  7,  1]])

In [ ]:
# Regularization Term ---> Pooling Layers ---->
# MinPooling
# Maxpooling
# GlobalAveragePooling


In [ ]:
# Stride ---> gap or step value that is use for matrix choice
# kernel ---.> Filteration

In [ ]:
a

array([[15, 12, 28],
       [33, 48, 31],
       [31,  7,  1]])

In [ ]:
# 2*2 Kernel ----> Stride =  1

In [ ]:
[26,36,34,24], [36,27,24,42]
[34,24,42,25], [24,42,25,18]

([34, 24, 42, 25], [24, 42, 25, 18])

In [ ]:
# MaxPooling Layer -->
# [36],[42],[42],[42]
# MinPooling Layer --->
# [24],[24],[24],[18]
# GlobalAveragePoolingLayer--->
# [30][30.25][31.25][27.25]

In [ ]:
a=np.random.randint(1,50,16).reshape(4,4)

In [ ]:
a

array([[32, 17, 26, 39],
       [ 1, 49, 39, 26],
       [10, 17, 29, 46],
       [40, 28, 38, 14]])

In [ ]:
# 2*2 Kernel --> stride =2

In [ ]:
[31,14,17,42],[10,32,5,47]
[49,25,34,7],[6,26,340,15]

([49, 25, 34, 7], [6, 26, 340, 15])

In [ ]:
# #Dense Layers ---> it is considered as a fully connected layer andd in this, outoyt of first layer
# will be input of second layer. it is working as like pipeline

In [ ]:
# convolutional layer ----> It is considered as partially connected layer. and in this we withdetect specific parts

In [ ]:
# pooling layer---> It is regularizqation techinque for image related data

In [ ]:
# Flatten Layer  ---> It will convert higher dimensional layer to 1-D array

In [ ]:
# Workflow of CNN ----->


In [ ]:
# # Data Ingestion  ---> Data Cleaning and Preprocessing ---> Model Sequential Architecture
# CNN_1 layer
# Pooling Layer
# CNN_2 layer
# Pooling Layer
# Flatten Layer(it will convert into 1-D)
# Dense Layer(pipeline)
# model compile
# Model.training
# Model.Prediction
# Model loss,accuracy